# Generated by Django 3.2.3 on 2021-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.FloatField(default=-1),
        ),
    ]
