# Generated by Django 3.2.3 on 2021-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210523_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='relate_real_estate',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
